version: '3.4'

services:
  api:
    container_name: firesideapi
    image: firesideapi:latest
    build:
      context: .
      dockerfile: Server.Dev.Dockerfile
    ports:
      - '3200:3200'
    environment:
      - SCYLLA_HOST=scylla
      - SCYLLA_PORT=9042
      - SCYLLA_KEYSPACE=pancakes
    depends_on:
      - scylla
    volumes:
      - ./app:/api/app
    networks:
      - maidbot

  scylla:
    container_name: firesidescylla
    image: firesidescylla:latest
    command: --experimental 1
    build:
      context: .
      dockerfile: Scylla.Dockerfile
    ports: ["9042:9042", "7199:7199"]
    networks:
      - maidbot


networks:
  maidbot:
    driver: bridge
