version: '3.4'

services:
  api:
    container_name: firesideapi
    image: firesideapi:latest
    build:
      context: .
      dockerfile: Server.Dev.Dockerfile
    ports:
      - '3200:3200'
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=pancakes
    depends_on:
      - cassandra
    volumes:
      - ./app:/api/app
    networks:
      - fireside

  cassandra:
    container_name: firesidecass
    image: 'bitnami/cassandra:latest'
    ports: ["9042:9042", "7199:7199"]
    networks:
      - fireside


networks:
  fireside:
    driver: bridge
